#!/usr/bin/python3 /etc/cloud_config.py

installationType="${installation_type}"
allowUploadDownload="${allow_upload_download}"
osVersion= "${os_version}"
templateName="${template_name}"
templateVersion="${template_version}"
isBlink="${is_blink}"
bootstrapScript64="${bootstrap_script64}"
location="${location}"
sicKey="${sic_key}"
tenantId="${tenant_id}"
virtualNetwork="${virtual_network}"
clusterName="${cluster_name}"
externalPrivateAddresses="${external_private_addresses}"
customMetrics="${enable_custom_metrics}"
